steps:
# Zbuduj obraz Docker dla back-endu
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/map-events-api:$COMMIT_SHA', './backend']
  id: 'Build Backend Image'

# Wypchnij obraz do Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/map-events-api:$COMMIT_SHA']
  id: 'Push Backend Image'

# Wdróż nową wersję obrazu na Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'map-events-api' # Twoja nazwa serwisu w Cloud Run
    - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/map-events-api:$COMMIT_SHA'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
  id: 'Deploy to Cloud Run'

# Zainstaluj zależności i zbuduj aplikację front-endową 
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'frontend'
  id: 'Install Frontend Dependencies'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'frontend'
  id: 'Build Frontend'

# Wdróż front-end na Firebase Hosting 
- name: 'gcr.io/google.com/cloudsdktool/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'npm install -g firebase-tools && firebase deploy --only hosting --project $PROJECT_ID --non-interactive'
  dir: 'frontend'
  id: 'Deploy to Firebase Hosting'

# Zapisz obrazy w Artifact Registry
images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/map-events-api:$COMMIT_SHA'

# Ustawienie zmiennych, które będą dostępne w procesie budowania
substitutions:
  _REGION: 'europe-central2' # lub inny region GCP

options:
  logging: CLOUD_LOGGING_ONLY # Włącz logowanie do Cloud Logging