steps:
  # --- KROKI DLA BACKENDU ---
  # 1. Zbuduj obraz kontenera Docker
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Backend Image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/map-events-api:${SHORT_SHA}'
      - './backend'

  # 2. Wyślij obraz do Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Backend Image'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/map-events-api:${SHORT_SHA}'

  # 3. Wdróż nową wersję na Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:slim'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'map-events-api' # Nazwa Twojej usługi w Cloud Run
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/map-events-api:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=ci-cd-service-account@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-sql-instances=healthy-result-469611-e9:europe-central2:event-map-db'

  # --- KROKI DLA FRONTENDU ---
  # 4. Zainstaluj zależności frontendu
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install Frontend Dependencies'
    dir: 'frontend'
    args: ['install']

  # 5. Zbuduj aplikację frontendową, wstrzykując sekrety
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build Frontend'
    dir: 'frontend'
    args: ['run', 'build']
    secretEnv: ['VITE_API_URL', 'VITE_GOOGLE_MAPS_API_KEY', 'VITE_GOOGLE_MAPS_ID']

  # 6. Wdróż frontend na Firebase Hosting
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Deploy to Firebase Hosting'
    dir: 'frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install -g firebase-tools && firebase deploy --only hosting --project $PROJECT_ID --non-interactive'

# Definiujemy, które sekrety z Secret Managera mają być dostępne
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/VITE_API_URL/versions/latest
    env: 'VITE_API_URL'
  - versionName: projects/$PROJECT_ID/secrets/VITE_GOOGLE_MAPS_API_KEY/versions/latest
    env: 'VITE_GOOGLE_MAPS_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/VITE_GOOGLE_MAPS_ID/versions/latest
    env: 'VITE_GOOGLE_MAPS_ID'

# Domyślne wartości zmiennych
substitutions:
  _REGION: 'europe-central2'

options:
  logging: CLOUD_LOGGING_ONLY