steps:
  # --- Backend Steps (Your original, working logic) ---
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/map-events-api:${_TAG}', './backend']
    id: 'Build Backend Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/map-events-api:${_TAG}']
    id: 'Push Backend Image'

  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:slim'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'map-events-api'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/map-events-api:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account=ci-cd-service-account@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--add-cloudsql-instances=healthy-result-469611-e9:europe-central2:event-map-db'
    id: 'Deploy to Cloud Run'

  # --- Frontend Steps (Your original logic + secrets) ---
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'frontend'
    id: 'Install Frontend Dependencies'

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'frontend'
    id: 'Build Frontend'
    # This is the necessary addition to inject your secrets
    secretEnv: ['VITE_API_URL', 'VITE_GOOGLE_MAPS_API_KEY', 'VITE_GOOGLE_MAPS_ID']

  # This is your original, working deployment step
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install -g firebase-tools && firebase deploy --only hosting --project $PROJECT_ID --non-interactive'
    dir: 'frontend'
    id: 'Deploy to Firebase Hosting'

# This section is required to make the secrets available to the 'secretEnv' step
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/VITE_API_URL/versions/latest
    env: 'VITE_API_URL'
  - versionName: projects/$PROJECT_ID/secrets/VITE_GOOGLE_MAPS_API_KEY/versions/latest
    env: 'VITE_GOOGLE_MAPS_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/VITE_GOOGLE_MAPS_ID/versions/latest
    env: 'VITE_GOOGLE_MAPS_ID'

substitutions:
  _REGION: 'europe-central2'
  _TAG: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY