steps:
  # --- Backend Steps ---
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/event-map-repo/map-events-api:${SHORT_SHA}', './backend']
    id: 'Build Backend Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/event-map-repo/map-events-api:${SHORT_SHA}']
    id: 'Push Backend Image'

  - name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:slim'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'map-events-api' # Nazwa Twojej usługi w Cloud Run
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/event-map-repo/map-events-api:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account=ci-cd-service-account@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-sql-instances=healthy-result-469611-e9:europe-central2:event-map-db' # Użyj poprawnej flagi dla 2nd Gen
    id: 'Deploy to Cloud Run'

  # --- Frontend Steps ---
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install Frontend Dependencies'
    dir: 'frontend'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build Frontend'
    dir: 'frontend'
    args: ['run', 'build']
    # ZMIANA: Wstrzykujemy sekrety jako zmienne środowiskowe na czas budowania
    secretEnv: ['VITE_API_URL', 'VITE_GOOGLE_MAPS_API_KEY', 'VITE_GOOGLE_MAPS_ID']

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Deploy to Firebase Hosting'
    dir: 'frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install -g firebase-tools && firebase deploy --only hosting --project $PROJECT_ID --non-interactive'

# ZMIANA: Definiujemy, które sekrety mają być dostępne dla tego builda
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/VITE_API_URL/versions/latest
    env: 'VITE_API_URL'
  - versionName: projects/$PROJECT_ID/secrets/VITE_GOOGLE_MAPS_API_KEY/versions/latest
    env: 'VITE_GOOGLE_MAPS_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/VITE_GOOGLE_MAPS_ID/versions/latest
    env: 'VITE_GOOGLE_MAPS_ID'

substitutions:
  _REGION: 'europe-central2'

options:
  logging: CLOUD_LOGGING_ONLY